# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Build OSTree Layers
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - id: k3s_info
      run: |
        VERSION=$(git -C k3s tag --points-at=HEAD | grep -v rc)
        TAG_VERSION=${VERSION/+/-}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT

    - uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - uses: docker/setup-buildx-action@v3
      id: buildx

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: Containerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/doubleu-labs/fcos-k3s:stable
          ghcr.io/doubleu-labs/fcos-k3s:stable-${{ steps.k3s_info.outputs.tag_version }}

    - uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        build-args: |
          K3S_VERSION=${{ steps.k3s_info.outputs.version }}
        file: Containerfile.bundle
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/doubleu-labs/fcos-k3s-bundled:stable
          ghcr.io/doubleu-labs/fcos-k3s-bundled:stable-${{ steps.k3s_info.outputs.tag_version }}
